### ISSUE TITLE
智能合约环境开发的部署问题

### ISSUE THREAD

**Issue by wangjingyi1** [MonteCarloClub/zdyf3#10]
智能合约的开发环境如何部署呢？在Ubuntu环境下运行，需要在本机Windows环境下搭建虚拟机环境吗？

**Comment by KofClubs** [comment]
是。目前远程主机10.176.40.46仅能作为运行环境，请勿尝试在远程主机开发、推送源代码以及编译可执行文件；所有开发、推送与编译都应在本地完成，目前的开发分支是`refactor`。
1. 在本地配置Linux环境，构建可执行文件。
2. 将可执行文件`scp`拷贝到远程主机运行与测试。

**Comment by KofClubs** [comment]
Done.
重构完成：https://github.com/MonteCarloClub/zdyf3/pull/12
