### ISSUE TITLE
DABE2020加解密代码，访问策略一复杂，就会报错。如下图

### ISSUE THREAD

**Issue by wangjingyi1** [MonteCarloClub/zdyf3#11]
[
![14692b80973ec37ca79daa2f4fddfd1](https://user-images.githubusercontent.com/37876058/227830079-7b904e53-3e43-4b27-a219-4a743ab7a216.jpg)
](url)

**Comment by KofClubs** [comment]
@dongliangCai 请在此PR修改：https://github.com/MonteCarloClub/dabe/pull/1

**Comment by KofClubs** [comment]
Merged: https://github.com/MonteCarloClub/dabe/pull/1
